run:
  timeout: 5m
  modules-download-mode: readonly
  go: '1.25.0'

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
  disable:
    - govet
    - staticcheck
    - unused
    - gocyclo
    - deadcode
    - varcheck
    - structcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
