name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Run tests
      run: |
        cd kproximate
        go mod tidy
        go test -v ./...
    
    - name: Build
      run: |
        cd kproximate
        go build -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Check formatting
      run: |
        cd kproximate
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted:"
          gofmt -l .
          exit 1
        fi
        echo "✓ Code is properly formatted"

  helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'
    
    - name: Update Helm dependencies
      run: helm dependency update chart/kproximate
    
    - name: Lint Helm chart
      run: helm lint chart/kproximate
    
    - name: Template Helm chart
      run: helm template test chart/kproximate --values examples/example-values-with-taints.yaml
